# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 781, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.ConnectTab = QtWidgets.QWidget()
        self.ConnectTab.setObjectName("ConnectTab")
        self.connectButton = QtWidgets.QPushButton(self.ConnectTab)
        self.connectButton.setGeometry(QtCore.QRect(190, 240, 88, 34))
        self.connectButton.setObjectName("connectButton")
        self.comboBox = QtWidgets.QComboBox(self.ConnectTab)
        self.comboBox.setGeometry(QtCore.QRect(80, 160, 291, 32))
        self.comboBox.setObjectName("comboBox")
        self.checkBox = QtWidgets.QCheckBox(self.ConnectTab)
        self.checkBox.setGeometry(QtCore.QRect(70, 80, 88, 22))
        self.checkBox.setObjectName("checkBox")
        self.scanButton = QtWidgets.QPushButton(self.ConnectTab)
        self.scanButton.setGeometry(QtCore.QRect(310, 240, 88, 34))
        self.scanButton.setObjectName("scanButton")
        self.tabWidget.addTab(self.ConnectTab, "")
        self.CommandsTab = QtWidgets.QWidget()
        self.CommandsTab.setObjectName("CommandsTab")
        self.cmdTxt = QtWidgets.QTextEdit(self.CommandsTab)
        self.cmdTxt.setGeometry(QtCore.QRect(43, 140, 271, 41))
        self.cmdTxt.setObjectName("cmdTxt")
        self.outTxt = QtWidgets.QPlainTextEdit(self.CommandsTab)
        self.outTxt.setGeometry(QtCore.QRect(40, 230, 371, 191))
        self.outTxt.setObjectName("outTxt")
        self.label = QtWidgets.QLabel(self.CommandsTab)
        self.label.setGeometry(QtCore.QRect(50, 200, 58, 18))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.CommandsTab)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 111, 18))
        self.label_5.setObjectName("label_5")
        self.SendButton = QtWidgets.QPushButton(self.CommandsTab)
        self.SendButton.setGeometry(QtCore.QRect(370, 140, 88, 34))
        self.SendButton.setObjectName("SendButton")
        self.tabWidget.addTab(self.CommandsTab, "")
        self.RecurringTab = QtWidgets.QWidget()
        self.RecurringTab.setObjectName("RecurringTab")
        self.reCmdTxt = QtWidgets.QTextEdit(self.RecurringTab)
        self.reCmdTxt.setGeometry(QtCore.QRect(60, 100, 271, 41))
        self.reCmdTxt.setObjectName("reCmdTxt")
        self.label_2 = QtWidgets.QLabel(self.RecurringTab)
        self.label_2.setGeometry(QtCore.QRect(70, 210, 58, 18))
        self.label_2.setObjectName("label_2")
        self.reOut = QtWidgets.QPlainTextEdit(self.RecurringTab)
        self.reOut.setGeometry(QtCore.QRect(60, 240, 371, 191))
        self.reOut.setObjectName("reOut")
        self.reTime = QtWidgets.QTextEdit(self.RecurringTab)
        self.reTime.setGeometry(QtCore.QRect(420, 100, 104, 41))
        self.reTime.setObjectName("reTime")
        self.label_3 = QtWidgets.QLabel(self.RecurringTab)
        self.label_3.setGeometry(QtCore.QRect(420, 70, 111, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.RecurringTab)
        self.label_4.setGeometry(QtCore.QRect(60, 70, 111, 18))
        self.label_4.setObjectName("label_4")
        self.SetButton = QtWidgets.QPushButton(self.RecurringTab)
        self.SetButton.setGeometry(QtCore.QRect(340, 160, 88, 34))
        self.SetButton.setObjectName("SetButton")
        self.tabWidget.addTab(self.RecurringTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "Connect"))
        self.checkBox.setText(_translate("MainWindow", "Enable tab"))
        self.scanButton.setText(_translate("MainWindow", "Scan"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ConnectTab), _translate("MainWindow", "Connect"))
        self.label.setText(_translate("MainWindow", "Output"))
        self.label_5.setText(_translate("MainWindow", "Command"))
        self.SendButton.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.CommandsTab), _translate("MainWindow", "Command"))
        self.label_2.setText(_translate("MainWindow", "Output"))
        self.label_3.setText(_translate("MainWindow", "Recurring time"))
        self.label_4.setText(_translate("MainWindow", "Command"))
        self.SetButton.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RecurringTab), _translate("MainWindow", "Recurring commands"))
